Repository Hobiday/Hobiday-frontend, pull requests merged in 2024-12, with the labels that each got.

#8 ✨ Feat: 소셜 로그인 기능 및 페이지 구현
  .vscode/settings.json
  @types/global.d.ts
  @types/images.d.ts
  @types/svgr.d.ts
  next.config.mjs
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/img/logo-image.png
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/_component/index.ts
  src/app/login/_component/intro-text.tsx
  src/app/login/_component/login-button.tsx
  src/app/login/_component/logo.tsx
  src/app/login/_component/policies.tsx
  src/app/login/_component/title.tsx
  src/app/login/page.tsx
  src/app/registration-form/page.tsx
  src/assets/icons/kakao-logo.svg
  src/assets/images/logo-image.svg
  src/assets/images/logo-title.svg
  src/contexts/providers/kakao-script.tsx
  tailwind.config.ts
  tsconfig.json
Labels: ✨ feat, 💄 style

#12 ♻️ Refactor: access 토큰 저장 방식 변경
  src/app/login/_component/policies.tsx
  src/app/registration-form/page.tsx
Labels: ♻️ refactor

#13 🔨 Chore: deploy.yml 수정
  .github/workflows/deploy.yml
  pnpm-lock.yaml
Labels: 🔧 chore

#18 🔨 Chore: 병합 충돌 해결
  .github/workflows/deploy.yml
  pnpm-lock.yaml
  src/app/login/_component/policies.tsx
Labels: 🔧 chore

#20 💄 Style: 홈페이지 UI 구성
  .github/workflows/deploy.yml
  pnpm-lock.yaml
  public/banner/caravaggio.svg
  public/banner/cyrano.svg
  public/banner/gwangHwaMun.svg
  public/banner/pirate.svg
  public/banner/shearMadness.svg
  public/banner/snowFlake.svg
  src/app/(main)/_component/banner/index.tsx
  src/app/(main)/_component/tabs/index.tsx
  src/app/(main)/feed/page.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/my/page.tsx
  src/app/(main)/page.tsx
  src/app/(main)/wishlist/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/commons/chip/index.tsx
  src/components/header/index.tsx
  src/components/navigation-bar/index.tsx
  src/components/navigation-bar/navigation-tab.tsx
  src/components/section-layout/index.tsx
  tailwind.config.ts
Labels: ✨ feat, 💄 style

#22 🔨 Chore: main-dev 버전 matching
  pnpm-lock.yaml
Labels: 🔧 chore

#23 🔨 Chore: dev rebase
  .eslintrc.json
  pnpm-lock.yaml
Labels: 🔧 chore

#24 🔨 Chore: pnpm-lock 재설치
  pnpm-lock.yaml
Labels: 🔧 chore

#26 🔨 Chore: github actions 재연결
  .github/workflows/deploy.yml
  build.sh
  src/app/(main)/page.tsx
Labels: 🔧 chore

#27 dev to main
  .github/workflows/deploy.yml
  build.sh
  src/app/(main)/page.tsx
Labels: 🚩end

#28 ✨ Feat: Tabs 컴포넌트 swiper 적용 및 Card 컴포넌트 제작
  package.json
  pnpm-lock.yaml
  src/app/(main)/_component/performance-list.tsx
  src/app/(main)/_component/tabs/index.tsx
  src/app/(main)/page.tsx
  src/components/card/card.stories.tsx
  src/components/card/index.tsx
  src/components/commons/chip/index.tsx
Labels: ✨ feat, 💄 style, ✅ test

#30 ✨ Feat: header 컴포넌트 제작
  public/img/logo-text.svg
  src/app/(main)/_component/banner/index.tsx
  src/app/(main)/_component/performance-list.tsx
  src/app/(main)/feed/page.tsx
  src/app/(main)/my/page.tsx
  src/app/(main)/page.tsx
  src/app/(main)/performance/page.tsx
  src/app/(main)/search/page.tsx
  src/app/(main)/wishlist/page.tsx
  src/components/commons/Icon/index.tsx
  src/components/header/index.tsx
  src/components/layout/index.ts
  src/components/layout/main-layout/index.tsx
  src/components/layout/section-layout/index.tsx
Labels: ✨ feat

#33 ✨ Feat: 피드 페이지, 피드 등록 페이지 제작
  package.json
  pnpm-lock.yaml
  src/app/(main)/feed/comments/page.tsx
  src/app/(main)/feed/page.tsx
  src/app/(main)/feed/upload/_component/add-info/index.tsx
  src/app/(main)/feed/upload/_component/category/index.tsx
  src/app/(main)/feed/upload/_component/hashtag-input/index.tsx
  src/app/(main)/feed/upload/_component/image-uploader/index.tsx
  src/app/(main)/feed/upload/_component/text-input/index.tsx
  src/app/(main)/feed/upload/page.tsx
  src/app/globals.css
  src/app/login/_component/login-button.tsx
  src/components/comment/index.tsx
  src/components/feed/comment-page.tsx
  src/components/feed/feed-page.tsx
  src/components/feed/index.tsx
  src/components/feed/upload-page.tsx
  src/components/header/index.tsx
  src/components/navigation-bar/index.tsx
  src/stores/useTextStore.ts
  src/stores/useUploadTextStore.ts
  src/utils/comment-gradient.tsx
  src/utils/like-gradient.tsx
  tailwind.config.ts
Labels: ✨ feat, 💄 style

#34 ✨ Feat: 공연 조회 api 연결 및 performance api adapter 추가
  .gitignore
  next.config.mjs
  src/apis/end-points.ts
  src/apis/index.ts
  src/apis/performance-api.ts
  src/app/(main)/_component/performance-list.tsx
  src/app/(main)/_component/tabs/index.tsx
  src/app/(main)/performance/[performanceId]/page.tsx
  src/app/apis/index.ts
  src/assets/icons/location.svg
  src/components/card/card.stories.tsx
  src/components/card/index.tsx
  src/components/commons/spinner/index.tsx
  src/constants/category.ts
  src/hooks/index.ts
  src/hooks/performance/use-performance-query.ts
  src/hooks/queries/index.ts
  src/hooks/queries/performance-keys.ts
  src/types/base-response.ts
  src/types/commons/pagination.ts
  src/types/index.ts
  src/types/performance/adapter/index.ts
  src/types/performance/adapter/performanceAdapter.ts
  src/types/performance/adapter/performanceDetailsAdapter.ts
  src/types/performance/client/index.ts
  src/types/performance/index.ts
  src/types/performance/performance-queries.ts
  src/types/performance/performance.type.ts
  src/types/performance/server/index.ts
  src/utils/api-error/api-error-messages.ts
  src/utils/api-error/error-handler.ts
Labels: ✨ feat, ♻️ refactor

#35 ✨ Feat: 검색 페이지 제작
  src/app/(main)/search/page.tsx
  src/components/layout/search-layout/index.tsx
  src/components/search-bar/index.tsx
  src/components/search/index.tsx
  src/components/search/recommend/index.tsx
  src/components/search/result/index.tsx
  src/stores/useSearchStore.ts
Labels: ✨ feat, 💄 style

#36 ✨ Feat: 피드, 댓글 정보 API 연결
  src/apis/comment-api.ts
  src/apis/end-points.ts
  src/apis/feed-api.ts
  src/app/(main)/feed/comments/page.tsx
  src/app/(main)/feed/page.tsx
  src/app/(main)/feed/upload/_component/add-info/index.tsx
  src/app/(main)/feed/upload/_component/category/index.tsx
  src/app/(main)/feed/upload/_component/hashtag-input/index.tsx
  src/app/(main)/feed/upload/_component/image-uploader/index.tsx
  src/app/(main)/feed/upload/_component/text-input/index.tsx
  src/app/(main)/feed/upload/page.tsx
  src/app/(main)/search/add-info/page.tsx
  src/app/login/_component/login-button.tsx
  src/app/registration-form/page.tsx
  src/components/comment/index.tsx
  src/components/feed/comment-page.tsx
  src/components/feed/comment/index.tsx
  src/components/feed/feed-page.tsx
  src/components/feed/index.tsx
  src/components/feed/item/feed-actions.tsx
  src/components/feed/item/feed-content.tsx
  src/components/feed/item/feed-hashtags.tsx
  src/components/feed/item/feed-image.tsx
  src/components/feed/item/feed-profile.tsx
  src/components/feed/item/index.tsx
  src/components/feed/modal/feed-menu.tsx
  src/components/feed/upload/index.tsx
  src/components/header/index.tsx
  src/components/modal/index.tsx
  src/components/search/add-info/index.tsx
  src/components/search/add-info/result.tsx
  src/components/search/card/index.tsx
  src/components/search/recommend/index.tsx
  src/components/search/result/index.tsx
  src/constants/category.ts
  src/hooks/feed/use-feed-query.ts
  src/hooks/queries/feed-keys.ts
  src/stores/useFeedStore.ts
  src/stores/useModalStore.ts
  src/stores/useTextStore.ts
  src/stores/useUploadTextStore.ts
  src/stores/useUserStore.ts
  src/types/comment/index.ts
  src/types/feed/feed.type.ts
  src/types/feed/index.ts
  src/types/user/index.ts
  src/utils/like-gradient-default.tsx
  src/utils/like-gradient-pressed.tsx
Labels: ✨ feat, ♻️ refactor

#37 ✨ Feat: 온보딩 레이아웃
  public/banner/temp-snowflake.svg
  src/apis/end-points.ts
  src/apis/onboarding-api.ts
  src/apis/performance-api.ts
  src/apis/user-api.ts
  src/app/(main)/_component/banner/index.tsx
  src/app/(main)/_components/banner/index.tsx
  src/app/(main)/_components/performance-list.tsx
  src/app/(main)/_components/tabs/index.tsx
  src/app/(main)/feed/page.tsx
  src/app/(main)/feed/upload/_component/add-info/index.tsx
  src/app/(main)/feed/upload/_component/category/index.tsx
  src/app/(main)/onborading/_components/category-step.tsx
  src/app/(main)/onborading/_components/complete-step.tsx
  src/app/(main)/onborading/_components/onboarding.tsx
  src/app/(main)/onborading/_components/profile-step.tsx
  src/app/(main)/onborading/page.tsx
  src/app/(main)/page.tsx
  src/app/(main)/performance/[performanceId]/_components/performance-detail.tsx
  src/app/(main)/performance/[performanceId]/page.tsx
  src/app/not-found.tsx
  src/assets/icons/calendar-month.svg
  src/assets/icons/location.svg
  src/components/card/index.tsx
  src/components/commons/funnel/index.tsx
  src/components/commons/gap/index.tsx
  src/components/feed/index.tsx
  src/components/header/index.tsx
  src/components/layout/main-layout/index.tsx
  src/components/progress-bar/index.tsx
  src/constants/category.ts
  src/hooks/index.ts
  src/hooks/performance/use-performance-query.ts
  src/hooks/queries/index.ts
  src/hooks/queries/performance-keys.ts
  src/hooks/use-debounce.ts
  src/hooks/use-funnel.tsx
  src/hooks/use-shallow-routing.tsx
  src/hooks/user/use-profile-registration.ts
  src/stores/use-onboarding.store.ts
  src/types/onboarding/index.ts
  src/types/performance/adapter/index.ts
  src/types/performance/adapter/performance-adapter.ts
  src/types/performance/adapter/performance-details-adapter.ts
  src/types/performance/adapter/performanceDetailsAdapter.ts
  src/types/performance/performance.type.ts
  src/types/user/index.ts
  tailwind.config.ts
Labels: ✨ feat

#41 dev to main
  src/app/(main)/feed/upload/_component/add-info/index.tsx
  src/app/(main)/feed/upload/_component/category/index.tsx
  src/app/(main)/feed/upload/_component/hashtag-input/index.tsx
  src/app/(main)/feed/upload/_component/image-uploader/index.tsx
  src/app/(main)/performance/[performanceId]/_components/performance-detail.tsx
  src/app/login/_component/login-button.tsx
  src/components/commons/icon/index.tsx
  src/components/commons/icons/index.tsx
  src/components/feed/modal/feed-menu.tsx
  src/components/header/index.tsx
  src/components/search-bar/index.tsx
  src/components/search/add-info/result.tsx
  src/components/search/result/index.tsx
Labels: 🚩end

#42 ✨ Feat: Feed 등록 데이터 연동, 이미지 저장 연동, 댓글 페이지 및 좋아요 연동
  src/app/(main)/feed/page.tsx
  src/app/(main)/feed/upload/_component/category/index.tsx
  src/app/(main)/feed/upload/_component/image-uploader/index.tsx
  src/app/(main)/feed/upload/page.tsx
  src/app/(main)/my/page.tsx
  src/components/comment/index.tsx
  src/components/feed/comment/index.tsx
  src/components/feed/index.tsx
  src/components/feed/item/feed-actions.tsx
  src/components/feed/item/feed-hashtags.tsx
  src/components/feed/item/feed-image.tsx
  src/components/feed/item/feed-profile.tsx
  src/components/feed/upload/index.tsx
  src/hooks/feed/use-feed-upload.ts
  src/hooks/feed/use-image-upload.ts
  src/stores/useUploadTextStore.ts
  src/types/feed/index.ts
  src/utils/get-refresh-cookie.ts
Labels: ✨ feat, ♻️ refactor

#55 🐛 Fix: 이미지 여러 장 업로드 시 이미지 보이지 않는 문제 해결
  src/components/feed/item/feed-image.tsx
  src/components/feed/upload/index.tsx
  src/hooks/feed/use-image-upload.ts
  src/stores/useUploadTextStore.ts
Labels: 🐛 bug, ♻️ refactor

#56 ✨ Feat: 마이페이지, 프로필 편집 페이지, 개별 피드 페이지 제작
  public/img/pencil-3d.svg
  src/apis/end-points.ts
  src/apis/feed-api.ts
  src/apis/user-api.ts
  src/app/(main)/feed/[feedId]/_components/index.tsx
  src/app/(main)/feed/[feedId]/page.tsx
  src/app/(main)/feed/upload/_component/category/index.tsx
  src/app/(main)/my/_components/myprofile.tsx
  src/app/(main)/my/_components/no-feed.tsx
  src/app/(main)/my/_components/profile-feed.tsx
  src/app/(main)/my/_components/profile-genres.tsx
  src/app/(main)/my/_components/profile-image.tsx
  src/app/(main)/my/_components/profile-name.tsx
  src/app/(main)/my/_components/profile-stats.tsx
  src/app/(main)/my/edit/_components/edit-genres.tsx
  src/app/(main)/my/edit/_components/edit-image.tsx
  src/app/(main)/my/edit/_components/edit-introduction.tsx
  src/app/(main)/my/edit/_components/edit-name.tsx
  src/app/(main)/my/edit/page.tsx
  src/app/(main)/my/page.tsx
  src/assets/icons/setting.svg
  src/assets/images/pencil-3d.svg
  src/components/bottom-sheet/index.tsx
  src/components/comment/index.tsx
  src/components/feed/item/feed-profile.tsx
  src/contexts/bottom-sheet.context.tsx
  src/hooks/user/use-profile-image-upload.ts
  src/hooks/user/use-profile-update.tsx
  tailwind.config.ts
Labels: ✨ feat, 🐛 bug

#57 ✨ Feat: 모달창 구현, 정보 카드 연결, 팔로잉/팔로워 페이지 제작 및 타인의 프로필 페이지 연결
  next.config.mjs
  src/apis/comment-api.ts
  src/apis/end-points.ts
  src/apis/feed-api.ts
  src/apis/performance-api.ts
  src/apis/user-api.ts
  src/app/(main)/feed/[feedId]/_components/index.tsx
  src/app/(main)/feed/[feedId]/page.tsx
  src/app/(main)/feed/upload/_component/add-info/index.tsx
  src/app/(main)/feed/upload/_component/category/index.tsx
  src/app/(main)/feed/upload/_component/hashtag-input/index.tsx
  src/app/(main)/feed/upload/_component/image-uploader/index.tsx
  src/app/(main)/feed/upload/page.tsx
  src/app/(main)/my/[profileId]/_components/index.tsx
  src/app/(main)/my/[profileId]/page.tsx
  src/app/(main)/my/_components/myprofile.tsx
  src/app/(main)/my/_components/profile-stats.tsx
  src/app/(main)/my/followers/_components/index.tsx
  src/app/(main)/my/followers/page.tsx
  src/app/(main)/my/following/_components/index.tsx
  src/app/(main)/my/following/page.tsx
  src/app/(main)/my/page.tsx
  src/app/(main)/my/setting/_components/index.tsx
  src/app/(main)/my/setting/page.tsx
  src/components/comment/index.tsx
  src/components/feed/comment/index.tsx
  src/components/feed/index.tsx
  src/components/feed/item/feed-profile.tsx
  src/components/feed/modal/feed-menu.tsx
  src/components/feed/upload/index.tsx
  src/components/follow/button.tsx
  src/components/follow/index.tsx
  src/components/modal/index.tsx
  src/components/navigation-bar/index.tsx
  src/components/search/add-info/result.tsx
  src/components/search/card/index.tsx
  src/contexts/modal.context.tsx
  src/stores/useModalStore.ts
  src/stores/useUploadTextStore.ts
  src/stores/useUserStore.ts
Labels: ✨ feat, 🐛 bug, ♻️ refactor

#58 💄 Design: 디자인 요소 수정
  src/app/(main)/feed/upload/_component/add-info/index.tsx
  src/app/(main)/my/[profileId]/page.tsx
  src/app/(main)/my/_components/profile-feed.tsx
  src/components/search/card/index.tsx
Labels: 💄 style

#61 dev to main(rebase 진행 완료)
  pnpm-lock.yaml
  src/apis/comment-api.ts
  src/apis/feed-api.ts
  src/apis/user-api.ts
  src/app/(main)/feed/[feedId]/page.tsx
  src/app/(main)/feed/comments/page.tsx
  src/app/(main)/my/[profileId]/page.tsx
  src/app/(main)/my/_components/myprofile.tsx
  src/app/(main)/my/_components/profile-stats.tsx
  src/app/(main)/my/edit/_components/edit-image.tsx
  src/app/(main)/my/edit/page.tsx
  src/app/(main)/my/page.tsx
  src/app/(main)/page.tsx
  src/components/feed/comment/index.tsx
  src/components/feed/item/feed-actions.tsx
  src/components/feed/item/feed-image.tsx
  src/components/feed/item/feed-profile.tsx
  src/components/search/add-info/result.tsx
Labels: 🚩end

#62 🐛 Fix: 위시(좋아요) 버그 수정, optimistic update 적용
  src/apis/wishlist-api.ts
  src/app/(main)/performance/[performanceId]/_components/index.tsx
  src/app/(main)/performance/[performanceId]/_components/performance-header.tsx
  src/hooks/wishlist/use-wishlist-query.ts
Labels: 🛠️ fix

#64 ✨ Feat: 공연 ID로 작성된 피드 조회 페이지 제작 및 api tanstack-query 교체
  next.config.mjs
  public/img/pencil-3d.png
  src/apis/comment-api.ts
  src/apis/end-points.ts
  src/apis/feed-api.ts
  src/apis/user-api.ts
  src/app/(main)/_components/performance-list.tsx
  src/app/(main)/feed/search/[performanceId]/_components/index.tsx
  src/app/(main)/feed/search/[performanceId]/page.tsx
  src/app/(main)/my/_components/myprofile.tsx
  src/app/(main)/my/_components/no-feed.tsx
  src/app/(main)/my/edit/_components/edit-genres.tsx
  src/app/(main)/my/edit/_components/edit-introduction.tsx
  src/app/(main)/my/edit/_components/edit-name.tsx
  src/app/(main)/my/edit/page.tsx
  src/app/(main)/my/followers/_components/index.tsx
  src/app/(main)/my/following/_components/index.tsx
  src/components/comment/index.tsx
  src/components/feed/comment/index.tsx
  src/components/feed/item/feed-profile.tsx
  src/components/follow/index.tsx
  src/hooks/comment/use-comment-query.ts
  src/hooks/feed/use-feed-query.ts
  src/hooks/queries/index.ts
  src/hooks/user/use-profile-image-upload.ts
  src/hooks/user/use-profile-update.ts
  src/hooks/user/use-profile-update.tsx
  src/types/comment/index.ts
  src/types/feed/index.ts
  src/types/user/index.ts
Labels: ✨ feat, ♻️ refactor

#65 Feat: 로그인 온보딩 위시리스트 추가
  public/login-onboarding/login-onboarding-wishlist.svg
  src/app/login/_component/slides/slide-wishlist.tsx
Labels: ✨ feat

#67 Hotfix: pnpm-lock 재설치
  pnpm-lock.yaml
Labels: 🚨 hotfix

#69 🐛 Fix: 마이페이지 그리드 조절, 선호 카테고리 '복합' 추가
  src/app/(main)/my/_components/profile-feed.tsx
  src/app/(main)/my/edit/_components/edit-genres.tsx
Labels: 🐛 bug

#70 Fix: navbar 기본 색상 변경 및 카테고리 재정렬
  public/login-onboarding/login-onboarding-wishlist.svg
  src/app/(main)/onboarding/_components/category-step.tsx
  src/app/(main)/onboarding/_components/complete-step.tsx
  src/app/layout.tsx
  src/app/login/_component/slides/slide-category.tsx
  src/app/login/_component/slides/slide-wishlist.tsx
  src/app/registration-form/page.tsx
  src/assets/svgr-icons/AccountDefault.tsx
  src/assets/svgr-icons/FeedDefault.tsx
  src/assets/svgr-icons/HeartDefault.tsx
  src/assets/svgr-icons/HomeDefault.tsx
  src/components/navigation-bar/index.tsx
  src/constants/category.ts
Labels: 🐛 bug, 💄 style

#71 dev to main
  public/login-onboarding/login-onboarding-wishlist.svg
  src/app/(main)/my/_components/profile-feed.tsx
  src/app/(main)/my/edit/_components/edit-genres.tsx
  src/app/(main)/onboarding/_components/category-step.tsx
  src/app/(main)/onboarding/_components/complete-step.tsx
  src/app/layout.tsx
  src/app/login/_component/slides/slide-category.tsx
  src/app/login/_component/slides/slide-wishlist.tsx
  src/app/registration-form/page.tsx
  src/assets/svgr-icons/AccountDefault.tsx
  src/assets/svgr-icons/FeedDefault.tsx
  src/assets/svgr-icons/HeartDefault.tsx
  src/assets/svgr-icons/HomeDefault.tsx
  src/components/navigation-bar/index.tsx
  src/constants/category.ts
Labels: 🚩end

#72 ✨ Feat: 토스트 팝업 적용, 타인의 프로필 페이지 팔로우 버튼 제작
  next.config.mjs
  src/app/(main)/_components/performance-list.tsx
  src/app/(main)/feed/search/[performanceId]/_components/index.tsx
  src/app/(main)/feed/upload/_component/image-uploader/index.tsx
  src/app/(main)/my/[profileId]/_components/index.tsx
  src/app/(main)/my/_components/myprofile.tsx
  src/app/(main)/my/edit/_components/edit-genres.tsx
  src/app/(main)/my/edit/_components/edit-introduction.tsx
  src/app/(main)/my/edit/_components/edit-name.tsx
  src/app/(main)/my/edit/page.tsx
  src/app/(main)/my/followers/_components/index.tsx
  src/app/(main)/my/following/_components/index.tsx
  src/app/(main)/my/setting/_components/index.tsx
  src/app/(main)/performance/[performanceId]/_components/index.tsx
  src/app/(main)/wishlist/_components/wishlist.tsx
  src/assets/icons/toast-false.svg
  src/assets/icons/toast-true.svg
  src/components/comment/index.tsx
  src/components/commons/toast/index.tsx
  src/components/feed/comment/index.tsx
  src/components/feed/index.tsx
  src/components/feed/modal/feed-menu.tsx
  src/components/feed/upload/index.tsx
  src/components/follow/button.tsx
  src/components/follow/index.tsx
  src/components/search/add-info/result.tsx
  src/components/search/result/index.tsx
  src/hooks/queries/index.ts
  src/hooks/user/use-profile-update.ts
  src/stores/useFeedStore.ts
  tailwind.config.ts
Labels: ✨ feat, ♻️ refactor

#73 dev to main
  next.config.mjs
  src/app/(main)/_components/performance-list.tsx
  src/app/(main)/feed/search/[performanceId]/_components/index.tsx
  src/app/(main)/feed/upload/_component/image-uploader/index.tsx
  src/app/(main)/my/[profileId]/_components/index.tsx
  src/app/(main)/my/_components/myprofile.tsx
  src/app/(main)/my/edit/_components/edit-genres.tsx
  src/app/(main)/my/edit/_components/edit-introduction.tsx
  src/app/(main)/my/edit/_components/edit-name.tsx
  src/app/(main)/my/edit/page.tsx
  src/app/(main)/my/followers/_components/index.tsx
  src/app/(main)/my/following/_components/index.tsx
  src/app/(main)/my/setting/_components/index.tsx
  src/app/(main)/performance/[performanceId]/_components/index.tsx
  src/app/(main)/wishlist/_components/wishlist.tsx
  src/assets/icons/toast-false.svg
  src/assets/icons/toast-true.svg
  src/components/comment/index.tsx
  src/components/commons/toast/index.tsx
  src/components/feed/comment/index.tsx
  src/components/feed/index.tsx
  src/components/feed/modal/feed-menu.tsx
  src/components/feed/upload/index.tsx
  src/components/follow/button.tsx
  src/components/follow/index.tsx
  src/components/search/add-info/result.tsx
  src/components/search/result/index.tsx
  src/hooks/queries/index.ts
  src/hooks/user/use-profile-update.ts
  src/stores/useFeedStore.ts
  tailwind.config.ts
Labels: 🚩end
