Repository Hobiday/Hobiday-frontend, pull requests merged in 2024-11, with the labels that each got.

#3 ✨ tailwind-cn 함수 추가 및 자동 배포 github action 파일 설정
  .github/workflows/deploy.yml
  .vscode/settings.json
  build.sh
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/components/button/button.tsx
  src/lib/tailwind-cn.tsx
  tsconfig.json
Labels: ✨ feat, 🔧 chore

#4 dev to main
  .eslintrc.json
  .github/workflows/deploy.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .vscode/settings.json
  README.md
  build.sh
  package.json
  pnpm-lock.yaml
  src/app/(main)/page.tsx
  src/app/apis/index.ts
  src/app/globals.css
  src/app/layout.tsx
  src/components/Spinner/index.ts
  src/components/Spinner/loading-spinner.tsx
  src/components/bottom-sheet/index.ts
  src/components/button/button.tsx
  src/components/button/index.ts
  src/components/checkbox/index.ts
  src/components/chip/index.ts
  src/components/dialog/index.ts
  src/components/header/index.ts
  src/components/navigation-bar/index.ts
  src/components/search-bar/index.ts
  src/lib/tailwind-cn.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  tailwind.config.ts
  tsconfig.json
Labels: 🚩end

#5 🔨 Chore: spinner 폴더명 소문자로 변경
  src/components/index.ts
  src/components/spinner/index.ts
  src/components/spinner/loading-spinner.tsx
Labels: 🔧 chore

#6 dev to main
  src/components/index.ts
  src/components/spinner/index.ts
  src/components/spinner/loading-spinner.tsx
Labels: 🚩end

#7 ✨ svgr 이용해 svg 파일 컴포넌트화 환경 설정
  .storybook/main.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/@types/images.d.ts
  src/@types/svgr.d.ts
  src/app/(main)/page.tsx
  src/assets/icons/account-default.svg
  src/assets/icons/account-pressed.svg
  src/assets/icons/arrow-back.svg
  src/assets/icons/arrow-bottom.svg
  src/assets/icons/arrow-forward.svg
  src/assets/icons/arrow-top.svg
  src/assets/icons/calendar-month.svg
  src/assets/icons/cancel.svg
  src/assets/icons/clock.svg
  src/assets/icons/comment-text.svg
  src/assets/icons/comment.svg
  src/assets/icons/dots-horizontal.svg
  src/assets/icons/dots-vertical.svg
  src/assets/icons/feed-default.svg
  src/assets/icons/feed-pressed.svg
  src/assets/icons/hashtag.svg
  src/assets/icons/heart-default.svg
  src/assets/icons/heart-pressed.svg
  src/assets/icons/home-default.svg
  src/assets/icons/home-pressed.svg
  src/assets/icons/pencil.svg
  src/assets/icons/plus-circle.svg
  src/assets/icons/search.svg
  src/assets/icons/tune.svg
  src/assets/icons/x.svg
  tsconfig.json
Labels: ✨ feat
