Repository Hobiday/Hobiday-frontend, pull requests merged in 2025-03, with the labels that each got.

#77 ♻️ Refactor: 공연 상세 페이지 최적화 & 타인의 마이페이지 레이아웃 수정
  next.config.mjs
  src/app/(main)/_components/banner/index.tsx
  src/app/(main)/my/[profileId]/_components/index.tsx
  src/app/(main)/my/_components/profile-genres.tsx
  src/app/(main)/my/_components/profile-image.tsx
  src/app/(main)/my/_components/profile-name.tsx
  src/app/(main)/my/_components/profile-stats.tsx
  src/app/(main)/performance/[performanceId]/_components/index.tsx
  src/app/(main)/performance/[performanceId]/_components/performance-header.tsx
  src/app/(main)/performance/[performanceId]/_components/performance-info.tsx
Labels: ♻️ refactor

#78 ✨ Feat: middleware 설정 및 파일명 컨벤션에 맞춰 수정
  public/img/logo-image.webp
  src/apis/comment-api.ts
  src/apis/feed-api.ts
  src/apis/index.ts
  src/apis/onboarding-api.ts
  src/apis/performance-api.ts
  src/apis/user-api.ts
  src/apis/wishlist-api.ts
  src/app/(main)/example/page.tsx
  src/app/(main)/feed/[feedId]/_components/index.tsx
  src/app/(main)/feed/upload/_component/add-info/index.tsx
  src/app/(main)/feed/upload/_component/category/index.tsx
  src/app/(main)/feed/upload/_component/image-uploader/index.tsx
  src/app/(main)/feed/upload/_component/text-input/index.tsx
  src/app/(main)/my/[profileId]/_components/index.tsx
  src/app/(main)/my/_components/myprofile.tsx
  src/app/(main)/my/edit/_components/edit-name.tsx
  src/app/(main)/my/edit/page.tsx
  src/app/(main)/my/followers/_components/index.tsx
  src/app/(main)/my/following/_components/index.tsx
  src/app/(main)/my/setting/_components/index.tsx
  src/app/(main)/onboarding/_components/complete-step.tsx
  src/app/(main)/onboarding/_components/profile-step.tsx
  src/app/(main)/page.tsx
  src/app/login/_component/login-button.tsx
  src/app/login/_component/logo.tsx
  src/app/login/page.tsx
  src/components/commons/text-field/index.tsx
  src/components/feed/comment/index.tsx
  src/components/feed/item/feed-actions.tsx
  src/components/feed/item/feed-profile.tsx
  src/components/feed/modal/feed-menu.tsx
  src/components/feed/upload/index.tsx
  src/components/search-bar/index.tsx
  src/components/search/add-info/index.tsx
  src/components/search/add-info/result.tsx
  src/components/search/index.tsx
  src/components/search/recommend/index.tsx
  src/components/search/result/index.tsx
  src/constants/index.ts
  src/hooks/user/use-profile-update.ts
  src/lib/index.ts
  src/middleware.ts
  src/services/index.ts
  src/stores/index.ts
  src/stores/use-search.store.ts
  src/stores/use-upload-text.store.ts
  src/stores/use-user.store.ts
  src/styles/gradients/comment-gradient.tsx
  src/styles/gradients/index.ts
  src/styles/gradients/like-gradient-default.tsx
  src/styles/gradients/like-gradient-pressed.tsx
  src/styles/index.ts
  src/utils/api-error/index.ts
  src/utils/index.ts
  src/utils/remove-auth-token.ts
Labels: ✨ feat, 🔧 chore, 🐛 bug, ♻️ refactor

#79 ✨ Feat: sentry 에러모니터링 툴 및 playwright 온보딩 테스트 추가(husky 연동)
  .gitignore
  .husky/pre-push
  next.config.mjs
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/(main)/performance/[performanceId]/_components/index.tsx
  src/app/global-error.tsx
  src/instrumentation.ts
  src/middleware.ts
  tests/example.spec.ts
  tests/global-setup.ts
  tests/onboarding.spec.ts
  tests/storage/logged-in-storage.json
  tests/storage/onboarding-storage.json
  tests/utils/tester-login-helper.ts
Labels: ✨ feat, ✅ test

#80 ♻️ Refactor: TanStack Query 리팩토링 미적용 부분 교체
  src/apis/feed-api.ts
  src/apis/user-api.ts
  src/components/feed/upload/index.tsx
  src/hooks/comment/use-comment-query.ts
  src/hooks/feed/use-feed-query.ts
  src/hooks/feed/use-feed-upload.ts
  src/hooks/feed/use-image-upload.ts
  src/hooks/queries/index.ts
  src/types/feed/index.ts
Labels: ♻️ refactor

#82 ✨ Feat: 공연 리스트 무한 스크롤 및 card 컴포넌트 리팩토링
  .gitignore
  package.json
  pnpm-lock.yaml
  src/app/(main)/_components/performance-list.tsx
  src/app/(main)/feed/search/[performanceId]/_components/index.tsx
  src/app/(main)/feed/search/[performanceId]/page.tsx
  src/app/(main)/onboarding/_components/category-step.tsx
  src/app/(main)/performance/[performanceId]/_components/performance-header.tsx
  src/app/(main)/wishlist/_components/wishlist.tsx
  src/assets/svgr-icons/HeartDefault.tsx
  src/assets/svgr-icons/LikeGradientDefault.tsx
  src/assets/svgr-icons/LikeGradientPressed.tsx
  src/components/card/card.stories.tsx
  src/components/card/index.tsx
  src/components/search/result/index.tsx
  src/constants/category.ts
  src/hooks/index.ts
  src/hooks/performance/use-performance-infinite-query.ts
  src/hooks/queries/index.ts
  src/hooks/use-infinite-scroll.ts
  src/middleware.ts
  tests/example.spec.ts
  tests/storage/.gitkeep
Labels: ✨ feat, 🔧 chore, 💄 style
